#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times but prints an additional Hi on 9th iteration
i="0"
while [ "$i" -le 9 ]
do
	echo Holberton School
	((i=i+1))
	if [ "$i" -eq 9 ]
	then
		echo Hi
	fi
done
